homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: imperial
  time_zone: America/Chicago
  customize: !include config/customization.yaml

mqtt:
  client_id: hass
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  username: !secret mqtt_username
  password: !secret mqtt_password

# Enables the frontend
frontend:

http:
  api_password: !secret api_password
#  ssl_certificate: !secret ssl_certificate
#  ssl_key: !secret ssl_key

alexa:
  intents:
    WhereAreWeIntent:
      speech:
        type: plaintext
        text: >
          {%- if is_state('device_tracker.adam_phone_aptracker', 'home') %}
            You are both home, you silly
          {%- else -%}
            Adam is at {{ states("device_tracker.adam_phone_aptracker") }}
          {% endif %}
    LocateIntent:
      speech:
        type: plaintext
        text: >
          {%- for state in states.device_tracker -%}
            {%- if state.name.lower() == User.lower() -%}
              {{ state.name }} is at {{ state.state }}
            {%- elif loop.last -%}
              I am sorry, I do not know where {{ User }} is.
            {%- endif -%}
          {%- else -%}
             Sorry, I don't have any trackers registered.
          {%- endfor -%}

# View all events in a logbook
logbook:

# Track the sun
sun:

# Text to speech
tts:
  platform: google
 
wemo: 
  static:
    - 192.168.0.105

binary_sensor: !include config/binary_sensor.yaml
sensor: !include_dir_list config/sensors/
camera: !include config/cameras.yaml
media_player: !include config/media_players.yaml
switch: !include config/switches.yaml
panel_custom: !include config/panel_custom.yaml
notify: !include config/notifications.yaml

automation: !include_dir_list config/automation/
group: !include config/groups.yaml

device_tracker: 
  - platform: owntracks

ifttt:
  key: !secret ifttt_api

tradfri:
  host: 192.168.0.106
  api_key: !secret tradfri_token
