homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: imperial
  time_zone: America/Chicago
  customize: !include config/customization.yaml

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  api_password: !secret api_password
  # base_url: greylurk.pagekite.me

discovery:
  ignore: 
    - plex_mediaserver

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Text to speech
tts:
  platform: google

switch:
  - platform: tplink
    host: 192.168.0.104
    name: Decker's Humidifier
  - platform: tplink
    host: 192.168.0.175
    name: Living Room Lights

camera:
  - platform: onvif
    name: Basement
    port: 8080
    host: 192.168.0.198
    username: !secret camera_username
    password: !secret camera_password
  - platform: onvif
    name: Living Room
    host: 192.168.0.102
    port: 8080
    username: !secret camera_username
    password: !secret camera_password

media_player:
  - platform: firetv
    name: Living Room FireTV
  - platform: cast
    host: 192.168.0.155
  - platform: cast
    host: 192.168.0.147

updater:
  include_used_components: true

mqtt:
  client_id: hass
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  username: !secret mqtt_username
  password: !secret mqtt_password

device_tracker: 
  - platform: owntracks

notify:
  - platform: facebook
    page_access_token: !secret fb_access_token
    name: Facebook
  - platform: nfandroidtv
    name: Living Room
    host: 192.168.0.193
  
http:
  api_password: !secret api_password

group: !include config/groups.yaml

panel_custom: !include config/panel_custom.yaml

binary_sensor: !include config/binary_sensor.yaml

sensor: !include config/sensors.yaml

ifttt:
  key: !secret ifttt_api
