homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: imperial
  time_zone: America/Chicago
  customize: !include config/customization.yaml

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  api_password: !secret api_password
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key

discovery:
  ignore: 
    - plex_mediaserver
    - google_cast

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Text to speech
tts:
  platform: google
 
wemo: 
  static:
    - 192.168.0.105

binary_sensor: !include config/binary_sensor.yaml
camera: !include config/cameras.yaml
media_player: !include config/media_players.yaml
switch: !include config/switches.yaml
panel_custom: !include config/panel_custom.yaml
sensor: !include config/sensors.yaml
notify: !include config/notifications.yaml

automation: !include_dir_list config/automation/

weather:
  - platform: yweather
    woeid: 2461928
    name: Northfield, MN

updater:
  include_used_components: true

mqtt:
  client_id: hass
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  username: !secret mqtt_username
  password: !secret mqtt_password

device_tracker: 
  - platform: owntracks

  
group: !include config/groups.yaml

ifttt:
  key: !secret ifttt_api
