id: lights_on
alias: Lights On
trigger:
  - entity_id: sun.sun
    from: above_horizon
    platform: state
    to: below_horizon
action:
  - entity_id: switch.living_room_lights
    service: light.turn_on
    data:
      entity_id: switch.living_room_lights
