alias: Commute Notification
trigger: 
  platform: numeric_state
  entity_id: sensor.home_to_transit
  above: '25'
condition:
  - condition: time
    after: '06:50:00'
    before: '07:25:00'
    weekday:
     - mon
     - tue
     - wed
     - thu
     - fri
action:
 - service: notify.pushbullet
   data: 
     title: Commute
     message: 'Traffic is heavy, over {{ states.sensor.home_to_transit.state }} minutes.'
