weather_overview:
  name: Weather Overview
  entities:
    - camera.msp_doppler
    - sensor.pws_weather_1d
    - sensor.pws_temp_high_record_f
    - sensor.pws_temp_high_1d_f
    - sensor.pws_temp_f
    - sensor.pws_feelslike_f
    - sensor.pws_heat_index_f
    - sensor.pws_temp_low_1d_f
    - sensor.pws_temp_low_record_f
    - sensor.pws_precip_1d
    - sensor.pws_precip_1d_in
    - sensor.pws_wind_mph
    - sensor.pws_wind_1d_kph
    - sensor.pws_alerts

people:
  name: People
  entities:
    - device_tracker.adam_phone_aptracker

living_room:
  name: Living Room
  entities: 
    - camera.living_room
    - switch.living_room_lights
    - light.living_room
    - light.left
    - light.right
    - media_player.living_room
    - media_player.living_room_fire

bedroom:
  name: Master Bedroom
  entities:
    - switch.bedside_light
    - media_player.bedroom
    - media_player.bedroom_fire
