weather_overview:
  name: Weather Overview
  entities:
    - sensor.pws_weather_1d
    - sensor.pws_temp_high_record_f
    - sensor.pws_temp_high_1d_f
    - sensor.pws_temp_f
    - sensor.pws_feelslike_f
    - sensor.pws_heat_index_f
    - sensor.pws_temp_low_1d_f
    - sensor.pws_temp_low_record_f
    - sensor.pws_precip_1d
    - sensor.pws_precip_1d_in
    - sensor.pws_wind_mph
    - sensor.pws_wind_1d_kph
    - sensor.pws_alerts

people:
  name: People
  entities:
    - device_tracker.adam_phone_aptracker

living_room:
  name: Living Room
  entities: 
    - media_player.living_room
    - switch.living_room_lights

zones:
  name: Zones
  entities:
    - binary_sensor.floorplan

bedroom:
  name: Master Bedroom
  entities:
    - media_player.bedroom
    - switch.bedroom_humidifier
