WhereAreWeIntent:
  speech:
    text: >
      {%- if is_state('device_tracker.adam_phone_aptracker', 'home') %}
        Everyone is at home
      {%- else -%}
        Adam is at {{ states("device_tracker.adam_phone_aptracker") }}
      {% endif %}
LocateIntent:
  speech:
    text: >
      {%- for state in states.device_tracker -%}
        {%- if state.name.lower() == User.lower() -%}
          {{ state.name }} is at {{ state.state }}
        {%- elif loop.last -%}
          I am sorry, I do not know where {{ User }} is.
        {%- endif -%}
      {%- else -%}
         Sorry, I don't have any trackers registered.
      {%- endfor -%}
