- platform: facebook
  page_access_token: !secret fb_access_token
  name: Facebook
- platform: nfandroidtv
  name: Living Room
  host: 192.168.0.193
- platform: pushbullet
  name: pushbullet
  api_key: !secret pushbullet_token
